### ISSUE TITLE
Feature request: night mode

### ISSUE THREAD

**Issue by lager1** [carlospolop/hacktricks#151]
Hi, 

thanks for this awesome project, you really did a great work on this. Would it be possible to implement night mode? I'd send a PR for that but there are no actual css sources in the repo so i can't do that directly. I think some other people would consider such a feature useful as well.

Keep up the good work :)

**Comment by carlospolop** [comment]
Hi @lager1,

Unfortunately to have a dark mode you need to upgrade (paying) the gitbook account.
So, unless you know anyone that wants to sponsor hacktricks to pay every month for the upgrade, or a way to get it for free I can't offer that mode (which is a pity because I would really like it also).
Anyone with anything else to add feel free to reopen the issue.
